package com.decadev.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "asylumcase")
public class AsylumCase {
    // citizenship, caseOutcome, completion, currentDate, asylumOffice
/// EL SALVADOR ,Grant ,10/25/2016 ,2021-05-28T05:04:38.000Z,  ZLA
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String citizenship;

    @DynamoDBAttribute
    private String caseOutcome;

    @DynamoDBAttribute
    private String completion;

    @DynamoDBAttribute
    private String currentDate;

    @DynamoDBAttribute
    private String asylumOffice;

}
